version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/gardenplace
  - source: /backend/authService/config.json
    destination: /etc/gardenplace/backend/authService
  - source: /backend/api/config.json
    destination: /etc/gardenplace/backend/api
permissions:
  - object: /webapps/gardenplace
    pattern: "**"
    owner: ec2-user
    mode: 777
    acls:
      - u:ec2-user:rw
    type:
      - directory
  - object: /etc/gardenplace/backend/authService/config.json
    owner: ec2-user
    mode: 777
    acls:
      - u:ec2-user:rw
    type:
      - file
  - object: /etc/gardenplace/backend/api/config.json
    owner: ec2-user
    mode: 777
    acls:
      - u:ec2-user:rw
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 5
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 5
      runas: root