version: 0.2

run-as: root

env:
  shell: bash
  variables:
    GOPATH: "/go/"
  exported-variables:
    - GOPATH
  secrets-manager:
    DB_USERNAME: gardenplace-db-credentials:username
    DB_PASSWORD: gardenplace-db-credentials:password
    DB_HOST: gardenplace-db-credentials:host
    DB_PORT: gardenplace-db-credentials:port

phases:
  install:
    runtime-versions:
      golang: latest
  build:
    commands:
      - cd backend/auth
      - go build
    finally:
      - cd
  post_build:
    commands:
      - |
        echo '
        {
          "UserDBConnectionString": "'$DB_USERNAME':'$DB_PASSWORD'@tcp('$DB_HOST':'$DB_PORT')/gardenplace"
        }' > $GOPATH/config.json