version: 0.2

run-as: root

env:
  shell: bash
  variables:
    AWS_REGION: us-east-2
  secrets-manager:
    DB_USERNAME: gardenplace-db-credentials:username
    DB_PASSWORD: gardenplace-db-credentials:password
    DB_HOST: gardenplace-db-credentials:host
    DB_PORT: gardenplace-db-credentials:port
    MAIL_ENDPOINT: gardenplace-mail:Endpoint
    MAIL_USERNAME: gardenplace-mail:Username
    MAIL_PASSWORD: gardenplace-mail:Password
    S3_ENDPOINT: gardenplace-s3-credentials:endpoint
    S3_BUCKET: gardenplace-s3-credentials:bucket
    S3_KEY_ROOT_DIR: gardenplace-s3-credentials:key-root-dir
    S3_ACCESS_KEY_ID: gardenplace-s3-credentials:access-key-id
    S3_SECRET_ACCESS_KEY: gardenplace-s3-credentials:secret-access-key
phases:
  install:
    runtime-versions:
      golang: latest
      nodejs: latest
    commands:
      - echo Installing api dependencies...
      - cd backend/api
      - yarn install
      - cd ../..
  build:
    commands:
      - echo Building authService...
      - cd backend/authService
      - go build
      - cd ../..
      - echo Building api...
      - cd backend/api
      - yarn build
      - cd ../..
      - function replaceConfig { sed -i 's/{'$1'}/'${!1}'/' config.json; }
    finally:
      - echo $(ls)
  post_build:
    commands:
      - echo Creating config.json for authService...
      - function replaceConfig { sed -i 's/{'$1'}/'${!1}'/' config.json; }
      - cd backend/authService
      - cp configTemplate.json config.json
      - replaceConfig DB_USERNAME
      - replaceConfig DB_PASSWORD
      - replaceConfig DB_HOST
      - replaceConfig DB_PORT
      - replaceConfig MAIL_ENDPOINT
      - replaceConfig MAIL_USERNAME
      - replaceConfig MAIL_PASSWORD
      - cd ../..
      - echo Creating config.json for api...
      - cd backend/api
      - cp configTemplate.json config.json
      - replaceConfig DB_USERNAME
      - replaceConfig DB_PASSWORD
      - replaceConfig DB_HOST
      - replaceConfig DB_PORT
      - replaceConfig MAIL_ENDPOINT
      - replaceConfig MAIL_USERNAME
      - replaceConfig MAIL_PASSWORD
      - replaceConfig S3_ENDPOINT
      - replaceConfig S3_BUCKET
      - replaceConfig S3_KEY_ROOT_DIR
      - replaceConfig S3_ACCESS_KEY_ID
      - replaceConfig S3_SECRET_ACCESS_KEY
    finally:
      - echo $(ls)
      - cd
artifacts:
  files:
    - backend/authService/authService
    - backend/authService/config.json
    - backend/api/config.json
    - appspec.yml
    - scripts/*